-- Script para crear la tabla articles_en en Supabase
-- Ejecuta este script en el SQL Editor de Supabase

CREATE TABLE public.articles_en (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  description text NOT NULL,
  slug text NOT NULL,
  subcategory text[] NOT NULL,
  content text NOT NULL,
  image text NOT NULL,
  CONSTRAINT articles_en_pkey PRIMARY KEY (id),
  CONSTRAINT articles_en_title_key UNIQUE (title)
) TABLESPACE pg_default;

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.articles_en ENABLE ROW LEVEL SECURITY;

-- Política para permitir INSERT a todos
CREATE POLICY "Allow public insert" ON public.articles_en
FOR INSERT 
TO public
WITH CHECK (true);

-- Política para permitir SELECT a todos
CREATE POLICY "Allow public select" ON public.articles_en
FOR SELECT 
TO public
USING (true);
